Modified Websites/webpage.
Qbix/Platform-History-v2 pull request #1347
Opened 2019-07-19 10:04 UTC by AndreyTepaykin

Now all Websites/webpage streams published by main community.
And grant access to logged user by Streams_Access row.
And sure fixed Websites_Webpage::fetchStream to use primary index.

2019-07-22 19:51 UTC, EGreg requested changes

2019-07-22 19:51 UTC, EGreg commented on platform/plugins/Websites/classes/Websites/Webpage.php
> +		$streams->publisherId = Users::communityId();
Give an option to override publisherId, by having second parameter in function,

`$publisherId = null` which if null becomes Users::communityId

2019-07-23 09:12 UTC, AndreyTepaykin commented on platform/plugins/Websites/classes/Websites/Webpage.php
> +		$streams->publisherId = Users::communityId();
Done.

2019-07-25 14:56 UTC, EGreg approved these changes

2019-07-25 14:56 UTC, merged