Websites
Qbix/Platform-History-v2 pull request #1406
Opened 2019-09-18 14:45 UTC by AndreyTepaykin

2019-09-18 17:55 UTC, EGreg commented on platform/plugins/Websites/web/js/tools/webpage/chat.js
> +		tool.chatTool.state.onMessagePost.set(function (ordinal) {
shouldn't it be something more like `onMessageRender` ?

2019-09-18 17:56 UTC, EGreg requested changes

2019-09-18 17:56 UTC, EGreg commented on platform/plugins/Websites/web/js/tools/webpage/chat.js
> +		tool.chatTool.state.onMessagePost.set(function (ordinal) {
this doesn't seem to be the time message is posted

2019-09-19 10:36 UTC, AndreyTepaykin commented on platform/plugins/Websites/web/js/tools/webpage/chat.js
> +		tool.chatTool.state.onMessagePost.set(function (ordinal) {
Changed onMessagePost to onMessageRender

2019-09-20 17:12 UTC, EGreg approved these changes

2019-09-20 17:12 UTC, merged