Fixed Places/areas tool.
Qbix/Platform-History-v2 pull request #1407
Opened 2019-09-19 11:55 UTC by AndreyTepaykin

I found that area can't select when typed.

2019-09-19 17:00 UTC, EGreg requested changes

2019-09-19 17:00 UTC, EGreg commented on platform/plugins/Places/web/js/tools/areas.js
> +								var previewTool = Q.Tool.from(element, "Streams/preview");
It might be on element, or it might be a parent, so please try both. Do this:

`Q.from($('element').closest('.Streams_preview_tool').add(element), 'Streams/preview')`

2019-09-19 17:00 UTC, EGreg commented on platform/plugins/Places/web/js/tools/areas.js
> +							$(".Streams_preview_tool:not(.Streams_related_composer)", this.element).addClass("Q_filter_result");
You sure it's ok to not also add class to `Streams_preview_container` ?
In that case - fine

2019-09-23 08:56 UTC, AndreyTepaykin commented on platform/plugins/Places/web/js/tools/areas.js
> +								var previewTool = Q.Tool.from(element, "Streams/preview");
1. We don't have Q.from, only Q.Tool.from

2. It's useless to pass multiple elements to Q.Tool.from, because:
if (Q.isArrayLike(toolElement)) {
	toolElement = toolElement[0];
}
in Q.js lines 4700-4702

3. In the changes below I add Q_filter_result class only  to Streams_preview_tool element.

2019-09-23 08:56 UTC, AndreyTepaykin commented on platform/plugins/Places/web/js/tools/areas.js
> +							$(".Streams_preview_tool:not(.Streams_related_composer)", this.element).addClass("Q_filter_result");
Yes it works I checked.

2019-09-23 15:58 UTC, EGreg commented on platform/plugins/Places/web/js/tools/areas.js
> +								var previewTool = Q.Tool.from(element, "Streams/preview");
You need to add class to parent, but if it parent doesn't exist, then you have to add it to element. Please fix that part.

2019-09-23 15:59 UTC, EGreg commented on platform/plugins/Places/web/js/tools/areas.js
> +								var previewTool = Q.Tool.from(element, "Streams/preview");
`Q.from($('element').closest('.Streams_preview_tool').add(element), 'Streams/preview')`

This code I wrote will accomplish that. It will create jQuery [parent, element] and take first one (parent), but if it's empty, then it will consist of [element] (and take first one - element). Understand?

2019-09-24 09:16 UTC, AndreyTepaykin commented on platform/plugins/Places/web/js/tools/areas.js
> +								var previewTool = Q.Tool.from(element, "Streams/preview");
Ok, done in last commit.

2019-09-27 00:17 UTC, EGreg approved these changes

2019-09-27 00:17 UTC, merged