Fixed method Places_Location::fromStream
Qbix/Platform-History-v2 pull request #1429
Opened 2019-10-22 12:32 UTC by AndreyTepaykin

2019-10-28 20:27 UTC, EGreg commented on platform/plugins/Places/classes/Places/Location.php
> +		$location = json_decode(Q::ifset($stream, 'location', null));
Use `Q::json_decode()`

2019-10-28 20:29 UTC, EGreg requested changes

2019-10-28 20:29 UTC, EGreg commented on platform/plugins/Places/classes/Places/Location.php
> +			return (array)$location;
instead of all this, and `(array)` here please use `try { Q::json_decode(..., true) } catch (Exception $e)` or maybe you dont want to catch exception

2019-10-29 09:18 UTC, AndreyTepaykin commented on platform/plugins/Places/classes/Places/Location.php
> +			return (array)$location;
Done in last commit.

2019-11-03 01:15 UTC, EGreg approved these changes

2019-11-03 01:15 UTC, merged