Implemented 'remove identifier'.
Qbix/Platform-History-v2 pull request #1475
Opened 2019-12-13 12:29 UTC by AndreyTepaykin

Added methods User->removeEmail, User->removeMobile and User->removeIdentifier.
Also added class Users_Exception_LastIdentifier to exclude remove last identifier.
And added handler Users/identifier/delete and call it from Streams/participating page.

2019-12-23 06:17 UTC, EGreg requested changes

2019-12-23 06:17 UTC, EGreg commented on platform/plugins/Streams/handlers/Streams/participating/response/content.php
> +	$emailSubscribed = $dbStreams->rawQuery("select state from users_email where userId='".$loggedUserId."' and address='".$user->emailAddress."'")->fetchDbRow();
I am not going to merge pull requests where you interpolate raw values because $user->emailAddress may somehow be poisoned for example. And also because this query is not even indexable for sharding if we need. Always avoid rawQuery unless you have no other choice. This same query can be rewritten PROPERLY:

`$emailSubscribed = Users_Email()->select('state')->where(array('userId' => $loggedInUserId', ...)->fetchDbRow();`

2019-12-23 13:46 UTC, AndreyTepaykin commented on platform/plugins/Streams/handlers/Streams/participating/response/content.php
> +	$emailSubscribed = $dbStreams->rawQuery("select state from users_email where userId='".$loggedUserId."' and address='".$user->emailAddress."'")->fetchDbRow();
Fixed in last commit. Look please.

2019-12-24 21:18 UTC, EGreg approved these changes

2019-12-24 21:18 UTC, merged