Modified Places_Location::stream method. When new location stream created, try to get timeZone and save to attributes.
Qbix/Platform-History-v2 pull request #1490
Opened 2020-01-20 12:37 UTC by AndreyTepaykin

2020-01-20 15:40 UTC, EGreg requested changes
Please make this an option in `$options`, and document it. It shouldn't be default.

2020-01-20 15:53 UTC, EGreg requested changes
One more change, please

Put `$options = array()` as last parameter, and document the option in YUI as you see in other places.
This is so that we can add many optional options in the future, without making user write ($publisherId, $streamName, true, false, null, 'blah') as we add more options, which is hard for anyone to understand what corresponds to what.

2020-01-20 16:22 UTC, AndreyTepaykin commented
Done.

2020-01-21 04:21 UTC, EGreg approved these changes

2020-01-21 04:21 UTC, merged