Places location
Qbix/Platform-History-v2 pull request #158
Opened 2017-04-05 16:51 UTC by AndreyTepaykin

2017-04-10 19:15 UTC, EGreg requested changes
@AndreyTepaykin Can you please rename the css file to `location.css` from `PlacesLocation.css` and carefully update the references to it everywhere? This is just so it is consistent with the regular convention.

2017-04-10 19:16 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +						document.location.reload();
Do not use `document.location.reload` when you can use `Q.handle(location.href)` ... the latter uses AJAX instead of reloading the whole page, which could break things like Cordova.

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +						document.location.reload();
Do not use document.location.reload when you can use Q.handle(location.href) ... the latter uses AJAX instead of reloading the whole page, which could break things like Cordova.

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/css/PlacesLocation.css
> +.Places_location_tool.Q_selected,
Please rename the file to `location.css` and update ALL references to it carefully, to match our convention.

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +				Users.login({
Instead of calling `Users.login`, please just throw an exception. The user of this tool is supposed to make sure that the user is already logged in. Do not allow the tool to be rendered otherwise.

Actually, you can show a useful interface to a user who is not logged-in also. Just don't show the "my saved locations" related tool, but you can show "My Current Location" button and a way to type in an address, why not. The user doesn't have to be logged in for it. Yes, please improve the tool to do that.

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +			Q.text.Places.Location = Q.extend(Q.text.Places.Location, {
Please move this outside the tool constructor, to line 12 or something. Otherwise, it gets executed every time the tool is rendered.

Do it like this:
```
	Q.setObject("Q.text.Places.Location", {
		jibjabTitle: "Create your own custom eCards with",
		topics: "topics",
		searchTopic: "search for any topic",
		recent: "recent",
		newTopic: "New Topic",
		newTemplate: "New Template",
		useThisTemplate: "Use This Template!",
		customizeImages: "Tap any image to change it.",
		customizeLinks: "Please enter the following URLs:"
	});
        Q.setObject("Q.text_en.Places.Location", Q.text.Places.Location);
```
and in the future I will make the platform do translations like this:
```
Q.extend(Q.text, Q["text_" + Q.info.language])
```
which will translate all strings properly, and tool can use them like this:
`Q.getObject("Q.text.Places.Location.foo");`

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +						tool.$(".otherLocation").tool('Places/address', {
Please namespace all your CSS classes. It should not be `otherLocation` but `Places_otherLocation` or better yet, `Places_Location_otherLocation` if it is just for the `Places_location` tool. Always do this when you make new CSS classes in plugins or apps.

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +									"Places/location": {
The indentation is becoming crazy here. Consider assigning the literal objects to variables with meaningful names, and then putting this variable instead of the literal object. Same with functions. Functions are "hoisted" to the top of the scope (i.e. inside another function) so you can even define them at the bottom of the scope, and use them "before" the definition.

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +		'<div data-location="other" class="Q_selected"><label>Other Location</label><div class="otherLocation"></div></div>'
Please call it "Enter an address". And namespace your CSS classes.

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +							tool.$(".Places_location_related").tool('Streams/related', {
I see you make empty divs and then activate tools on them if something is set in the state.

This is fine. But I think a slightly more "logical" way is to pass the state variables to `Q.Template.render` and use
```
{{#if useRelatedLocations}}
  {{&tool "Places/location" "myCoolToolId"}}
{{/if}}
```

you can also pass the fields to the tool like this:

```
Q.Templates.render(templateName, {
     'Places/location': { options for all such tools },
     'id:myCoolToolId': { just for a single one }
}, callback);
```

Again, you don't have to do it, you can have empty divs like here. It's just a question of using declarative syntax to place tools inside template, or this way. Either way is ok.

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +											// please see Streams/preview documentation for preprocess option
very good!!

2017-04-10 19:39 UTC, EGreg commented on platform/plugins/Places/web/js/tools/location.js
> +					console.warn("ERROR(" + err.code + "): " + err.message);
When you do `console.warn` or `console.log` you should prefix all your messages with something like this:

Places.location.getCurrentPosition: error blabla

2017-04-13 05:14 UTC, EGreg commented on .gitignore
> +platform/plugins/Streams/web/img/icons.lnk
what is this about?

2017-04-13 05:14 UTC, EGreg commented on platform/plugins/Places/classes/Places/Location.php
> +		$json = file_get_contents($url);
if you aren't going to use curl, then remove the curl-related lines

2017-04-13 05:14 UTC, EGreg commented on platform/plugins/Places/classes/Places.php
> +		//$json = curl_exec($ch);
if you aren't going to use curl, then remove the curl-related lines

2017-04-14 16:14 UTC, EGreg commented
Just do these last changes and I will merge the pull request.

2017-04-14 16:14 UTC, EGreg approved these changes

2017-04-18 12:26 UTC, AndreyTepaykin commented on platform/plugins/Places/classes/Places.php
> +		//$json = curl_exec($ch);
Done

2017-04-18 12:27 UTC, AndreyTepaykin commented
Seems all changes done.
Please review again.

2017-04-25 02:50 UTC, merged