Fixed 1.1.6-Streams.mysql.php installation script:
Qbix/Platform-History-v2 pull request #1747
Opened 2021-11-29 10:30 UTC by AndreyTepaykin

1) Together with create profiles added ability to update exitsting profiles too.
2) Skip communities users.
3) Set/update not only profile title but icon too, because in search results need to show icon.

2021-12-01 19:50 UTC, EGreg reviewed
Why, what is wrong with the script you are replacing?
I removed 1.1.5

2021-12-01 20:12 UTC, AndreyTepaykin commented
1. Your script just create new profile, but don't update existings.
2. Your script created prodiles for communities too.
3. Your script doesn't set icon of profile stream.

2021-12-03 17:45 UTC, EGreg requested changes

2021-12-03 17:45 UTC, EGreg commented on platform/plugins/Streams/scripts/Streams/1.1.6-Streams.mysql.php
> +			if (Users::isCommunityId($user->id)) {
Keep your code but please restore lines 8 - 16, we can do this to be more efficient (why fetch all users, just need to fetch user Ids)

2021-12-03 17:45 UTC, EGreg commented on platform/plugins/Streams/scripts/Streams/1.1.6-Streams.mysql.php
> +			$stream = Streams::fetchOne($user->id, $user->id, $streamName);
Similarly here, I want you to be able to select in one database query, so it can be a lot faster to run the installer for many straems.

2021-12-03 17:45 UTC, EGreg commented on platform/plugins/Streams/scripts/Streams/1.1.6-Streams.mysql.php
> +				Streams::create($user->id, $user->id, $streamName, array(
Unfortunately, we can't create streams for many publishers in bulk, but for one publisher we can. Anyway, here you can leave as is, but use $userId everywhere

2022-01-10 23:54 UTC, EGreg commented on platform/plugins/Streams/scripts/Streams/1.1.6-Streams.mysql.php
> +				Streams::create($user->id, $user->id, $streamName, array(
@AndreyTepaykin take a look at this next week with me

2022-01-31 10:20 UTC, closed without merging