Grant credits for filling in profile streams by user.
Qbix/Platform-History-v2 pull request #1907
Opened 2022-10-14 12:47 UTC by AndreyTepaykin

2022-10-14 20:57 UTC, EGreg requested changes

2022-10-14 20:57 UTC, EGreg commented on platform/plugins/Assets/config/plugin.json
> +					"Streams/user/height": 1,
Add also Streams/user/firstname and Streams/user/lastname each 5

2022-10-14 20:57 UTC, EGreg commented on platform/plugins/Assets/handlers/Assets/after/Streams_save.php
> +function nft_update_attributes_relations ($params) {
Rename to Assets_NFT_update... and Asserts_grant_credits...

2022-10-14 20:57 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +        "IvitedUserFilledStream": "{{invitedUserName}} filled {{FilledStreamTitle}}",
You misspelled "Invited"!!

2022-10-14 20:57 UTC, EGreg commented on platform/plugins/Users/classes/Users.php
> +	static function isCustomIcon ($icon, $imported=true) {
Instead make it $unlessImported = false

2022-10-17 12:45 UTC, AndreyTepaykin commented on platform/plugins/Assets/config/plugin.json
> +					"Streams/user/height": 1,
Done

2022-10-17 12:45 UTC, AndreyTepaykin commented on platform/plugins/Assets/text/Assets/content/en.json
> +        "IvitedUserFilledStream": "{{invitedUserName}} filled {{FilledStreamTitle}}",
Fixed

2022-10-17 12:45 UTC, AndreyTepaykin commented on platform/plugins/Assets/handlers/Assets/after/Streams_save.php
> +function nft_update_attributes_relations ($params) {
Done

2022-10-17 12:46 UTC, AndreyTepaykin commented on platform/plugins/Users/classes/Users.php
> +	static function isCustomIcon ($icon, $imported=true) {
Done

2022-10-19 23:57 UTC, EGreg approved these changes

2022-10-19 23:57 UTC, merged