Updated Streams/batch handler and Streams/inplace/tool to allow create users streams on demand
Qbix/Platform-History-v2 pull request #1909
Opened 2022-10-18 13:25 UTC by AndreyTepaykin

2022-10-19 17:28 UTC, EGreg requested changes

2022-10-19 17:28 UTC, EGreg commented on platform/plugins/Streams/handlers/Streams/stream/post.php
> -			foreach (Base_Streams_Stream::fieldNames() as $f) {
Why did you remove this? We need to copy the fields!!
I don't see it in the resulting code. Please bring it back.
And I think the type has to match. This code was correct

2022-10-19 17:28 UTC, EGreg commented on platform/plugins/Streams/handlers/Streams/batch/response/batch.php
> +					// try to create stream if possible
You said this would only happen for possibleUserStreams, and if the user has authorization to create it. You should try / catch here to make sure the exception for creating the stream doesn't bring down the rest of the batch request (instead, we can return the MissingRow and move on).

2022-10-20 10:59 UTC, AndreyTepaykin commented on platform/plugins/Streams/handlers/Streams/stream/post.php
> -			foreach (Base_Streams_Stream::fieldNames() as $f) {
fixed in commit https://github.com/Qbix/Platform/pull/1909/commits/03cbfbdc4ac5c832f584eac58eed49a9a4a29732

2022-10-20 11:00 UTC, AndreyTepaykin commented on platform/plugins/Streams/handlers/Streams/batch/response/batch.php
> +					// try to create stream if possible
There is already exists try/catch in the body of foreach circle.

2022-10-21 15:36 UTC, EGreg approved these changes

2022-10-21 15:36 UTC, merged