Streams inplace
Qbix/Platform-History-v2 pull request #1933
Opened 2022-11-11 15:55 UTC by AndreyTepaykin

2022-11-11 17:08 UTC, EGreg requested changes
Whatever you change in Q.getter in web/Q.js also change it in classes/Q.js

2022-11-11 17:11 UTC, EGreg requested changes
Whatever you change in Q.getter in web/Q.js also change it in classes/Q.js

2022-11-11 17:11 UTC, EGreg commented on platform/plugins/Streams/text/Streams/content/en.json
> +        "StreamDoesntExists": "stream don't exists",
it should be StreamDoesntExist not "exists" with value "This stream doesn't exist", and we already have error "MissingStream" so we should have "Stream is missing." instead.

2022-11-11 17:11 UTC, EGreg commented on platform/plugins/Streams/text/Streams/content/en.json
> +        "NotEnoughPermissionsHandleStream": "not enough permissions to handle stream",
What is wrong to throw "Users_NotAuthorized" error?

2022-11-11 17:11 UTC, EGreg commented on platform/plugins/Streams/handlers/Streams/inplace/tool.php
> -		$field = !empty($options['field']) ? $options['field'] : 'content';
Seems you deleted a lot of code, can you summarize what you did here?

2022-11-11 17:21 UTC, AndreyTepaykin commented on platform/plugins/Streams/handlers/Streams/inplace/tool.php
> -		$field = !empty($options['field']) ? $options['field'] : 'content';
Please look demo video

2022-11-13 05:34 UTC, EGreg requested changes

2022-11-13 05:34 UTC, EGreg commented on platform/plugins/Streams/web/js/tools/inplace.js
> +		var value = state.fallback || (state.attribute ? stream.getAttribute(state.attribute) : stream.fields[state.field]) || "";
You got it backwards ... value is supposed to be `(stream && (state.attribute ? stream.getAttribute(state.attribute) : stream.fields[state.field])) || state.fallback || ""`

2022-11-14 12:10 UTC, AndreyTepaykin commented on platform/plugins/Streams/handlers/Streams/inplace/tool.php
> -		$field = !empty($options['field']) ? $options['field'] : 'content';
Explanation about removed code: https://drive.google.com/file/d/1lwS1KI8Kxly27ldewfTfB9VcOrZjmYFq/view?usp=sharing

2022-11-14 12:11 UTC, AndreyTepaykin commented on platform/plugins/Streams/text/Streams/content/en.json
> +        "StreamDoesntExists": "stream don't exists",
Use error message "Streams/inplace tool: stream is undefined" as tool content when 
publisherId or streamName undefined. This message used before, but as Exception.
So the text "StreamDoesntExists" don't need.
Commit: https://github.com/Qbix/Platform/pull/1933/commits/e9172bb862712a20c1996e4df290f5e869ef2e86

2022-11-14 12:11 UTC, AndreyTepaykin commented on platform/plugins/Streams/text/Streams/content/en.json
> +        "NotEnoughPermissionsHandleStream": "not enough permissions to handle stream",
Removed checking $stream->testWriteLevel('suggest') on server side. Because first of 
all this check only necessary if state.editable==true, but second (and most important) 
this checked on client side, and if state.editable==true but logged in user have no permissions, 
inplace rendered as non editable, i.e. just display stream content in tool container.
Commit: https://github.com/Qbix/Platform/pull/1933/commits/63a2f2aa7bd2f8d63cc55a51b5aa1f54a29608dc

2022-11-14 12:12 UTC, AndreyTepaykin commented on platform/plugins/Streams/web/js/tools/inplace.js
> +		var value = state.fallback || (state.attribute ? stream.getAttribute(state.attribute) : stream.fields[state.field]) || "";
Fixed value definition. First check if stream exists.
Commit: https://github.com/Qbix/Platform/pull/1933/commits/4c4f6bd14edb62afd22a7c8f8fc665fa62982c75

2022-11-16 17:55 UTC, EGreg approved these changes

2022-11-16 17:55 UTC, merged