Fixed bug in Streams::invite method. If invited user name undefined, does not need to be defined as inviting user name.
Qbix/Platform-History-v2 pull request #1969
Opened 2022-12-15 12:24 UTC by AndreyTepaykin

2022-12-16 04:03 UTC, EGreg requested changes
I changed displayName in invites to be fullName (even though that may violate access) because I was getting some sort of errors with null->foo later. Probably when sending an email which says "X invited you."
Maybe we should just put "Someone" in the user's language? Probably we should have a function like Streams_Avatar::anonymousName() which returns "Someone" in their language. Can you do that, and just assign it in PHP? Because it's sent to Node and Node just uses it.

2022-12-16 04:03 UTC, EGreg commented on platform/plugins/Streams/classes/Streams.php
> +			$stream = Streams::create($publisherId, $publisherId, 'Streams/interest', array(
No, this is the wrong fix. We still want to do access control. We just want the access control to be set properly. Please read this totally! ---> https://qbix.com/platform/guide/access#creating

2022-12-19 09:45 UTC, AndreyTepaykin commented on platform/plugins/Streams/classes/Streams.php
> +			$stream = Streams::create($publisherId, $publisherId, 'Streams/interest', array(
already changed, look please: https://drive.google.com/file/d/1ze8ER3a864ucBkIK6d56LqK5a85zmLxW/view?usp=sharing

2022-12-20 00:01 UTC, EGreg approved these changes

2022-12-20 00:01 UTC, merged

2022-12-20 00:03 UTC, EGreg commented on platform/plugins/Streams/classes/Streams.php
> +			$stream = Streams::create($publisherId, $publisherId, 'Streams/interest', array(
@AndreyTepaykin yes but where is the installer script that installs permissions to create a new conversation?

I see we have `Communities::newEventAuthorized()` that does this:
```
$anyoneNewEvent = Q_Config::get('Communities', 'events', 'anyoneNewEvent', false);
```

Maybe we should also have one for Conversation like Event?

On the other hand, why do we even have this config if we can add permissions with an installer, and manage them by admins?

2022-12-20 11:36 UTC, AndreyTepaykin commented on platform/plugins/Streams/classes/Streams.php
> +			$stream = Streams::create($publisherId, $publisherId, 'Streams/interest', array(
It's much faster and easyer to change permission by config. Opposite to streams permissions need to create installer script and make install, we can change default permission in plugin and it will take effect in all apps.
Second reason is hard to get labels which have permissions to manage stream (for example to throw Users_Exception_NotAuthorized on management page). While we can easy get labels list from config.
I see in config you added "canCreate" setting and used in Streams::canCreateStreamType method. Seems you think same way. May be we can add setting "canManage" and change method Streams::calculateAccess to use it?

2022-12-20 14:51 UTC, EGreg commented on platform/plugins/Streams/classes/Streams.php
> +			$stream = Streams::create($publisherId, $publisherId, 'Streams/interest', array(
Good point about Streams::canCreateStreamType method!

it seems that it checks config first, for roles related to publisher, as an easy check without going into database

and if not enough permissions, then checks database next (templates)

so one way to grant permissions for anyone to create an event in a community would be to have “” as a possible role in canCreate

on the other hand, what is “anyone”? The user still has to be logged in at least. 

And furthermore, I am starting to distrust idea of “anyone” regardless
of role. All people who join a community might be assigned an automatic role like “guest” or “member”. Or they might earn some credits.

Maybe we can have quotas for “anyone” to restrict how many events, conversations they can make, and then relax it for certain roles.