tool "Assets/web3/coin/presale/admin"
Qbix/Platform-History-v2 pull request #2108
Opened 2023-07-20 15:29 UTC by artman325

- change format in `platform/plugins/Assets/config/plugin.json`, section: Users.web3.contracts
- created `Q.Users.Web3.validate` sections for validate user input in tools
- created tool "Assets/web3/coin/presale/admin"
With this tool, anyone can produce [FundContract](https://github.com/Intercoin/fundContract/) and already have a view created.

Example to initiate
```php 
echo Q::tool("Assets/web3/coin/presale/admin", array(
        "chainId" => "0x13881"
)) 
```
 
 P.S. such pull request contain changes on master branch, see [merge with master branch](https://github.com/Qbix/Platform/commit/661b87b514cea1c439db95b38a07355879e927d5)

2023-07-26 20:28 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +						"roleId": "Role id"
Role ID

2023-07-26 20:29 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +						"timestamps": "Untiltime",
Did you mean to say "Until Time"

2023-07-26 20:29 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +						"thresholds": "token, Threshold",
"Token, Threshold" ?

2023-07-26 20:29 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +						"whitelistData": "whitelist Data",
Did you mean "Whitelist Data"?

What is this, some geeky info ? It needs to be user friendly.

2023-07-26 20:30 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +						"methodkeccack": "4bytes hash of method to check",
why would this be a user-facing string? can you remove all this stuff if it's not in the final UX?

2023-07-26 20:30 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +							"option0":"Owner can not withdraw",
Owner can't withdraw (everywhere you say can not)

2023-07-26 20:30 UTC, EGreg commented on platform/plugins/Assets/web/js/Assets.js
> +				'{{Q}}/pickadate/themes/default.css',
Are you still using pickadate?

2023-07-26 20:31 UTC, EGreg requested changes
Please see comments, they mostly have to do with cleaning up the text files

2023-07-27 12:03 UTC, artman325 commented
it's old version tool "Assets/web3/coin/presale/admin".
after all fixes and redesign will be in pull request [tools: "Assets/web3/coin/presale/admin" and "Assets/web3/coin/presale/buy"](https://github.com/Qbix/Platform/pull/2110)

2023-07-27 12:03 UTC, closed without merging