tools: "Assets/web3/coin/presale/admin" and "Assets/web3/coin/presale/buy"
Qbix/Platform-History-v2 pull request #2110
Opened 2023-07-26 15:37 UTC by artman325

Example to initiate
```
echo Q::tool("Assets/web3/coin/presale/buy", array(
        "chainId" => "0x13881",
        //"showShortInfo" => true,
        //"fund" => '0xcebbe553d62E4710BaAc52666D749Bbc35f40428'
)) 
```
P.S. this pull request is a continued of previous pull request https://github.com/Qbix/Platform/pull/2108

2023-07-26 20:32 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +						"methodkeccack": "4bytes hash of method to check",
please fix the language files to not have this kind of stuff, it's only for user-facing strings that make it into the final UX

2023-07-26 20:32 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +						"roleId": "index of role id"
ID not id, in user-facing

2023-07-26 20:32 UTC, EGreg commented on platform/plugins/Assets/text/Assets/content/en.json
> +							"option0":"Owner can not withdraw",
put "can't" everywhere you say "can not"

2023-07-26 20:33 UTC, EGreg requested changes
See comments, it's about text files

2023-07-27 11:54 UTC, artman325 commented on platform/plugins/Assets/text/Assets/content/en.json
> +						"roleId": "index of role id"
fixed

2023-07-27 11:54 UTC, artman325 commented on platform/plugins/Assets/text/Assets/content/en.json
> +						"methodkeccack": "4bytes hash of method to check",
fixed

2023-07-27 11:55 UTC, artman325 commented on platform/plugins/Assets/text/Assets/content/en.json
> +							"option0":"Owner can not withdraw",
done

2023-07-27 23:02 UTC, EGreg approved these changes

2023-07-27 23:02 UTC, merged