Users device
Qbix/Platform-History-v2 pull request #539
Opened 2017-10-20 20:13 UTC by jkokh

2017-10-23 12:57 UTC, EGreg requested changes
Please test it with a debugger, all lines look at the values of variables

2017-10-25 18:21 UTC, EGreg commented
Did you check everything yet?

2017-10-25 18:21 UTC, EGreg requested changes

2017-10-25 18:21 UTC, EGreg commented on platform/plugins/Users/web/js/UsersDevice.js
> +			this.getAdapter(function(adapter, err) {
Found more problems ... err should be first parameter, not second! Node-style. Change it everywhere.

2017-10-25 18:39 UTC, jkokh commented on platform/plugins/Users/web/js/UsersDevice.js
> +			this.getAdapter(function(adapter, err) {
ok

2017-11-01 17:07 UTC, EGreg approved these changes

2017-11-01 17:07 UTC, merged