When user join the stream, Streams::join check whether $options['subs…
Qbix/Platform-History-v2 pull request #774
Opened 2018-05-10 13:25 UTC by AndreyTepaykin

…cribed'] defined (line 2750). And change $participant->subscribed only if $options['subscribed'] defined.

But then you make Streams_Participant::update with 'subscribed' = $subscribed. So you change 'subscribed' anyway.
I wonder why you don't use $participant row, which already prepared for save?

2018-05-24 04:43 UTC, EGreg reviewed
Please explain what you are doing here. I don't understand

2018-05-24 04:45 UTC, EGreg approved these changes

2018-05-24 04:45 UTC, EGreg requested changes
Put it back how it was, unless it has a bug

2018-05-25 11:09 UTC, AndreyTepaykin commented
Fixed this pull request. Please check.

2018-05-30 22:26 UTC, EGreg approved these changes

2018-05-30 22:26 UTC, merged