Remove all actions with table users_device from backend.
Qbix/Platform-History-v2 pull request #777
Opened 2018-05-22 12:51 UTC by AndreyTepaykin

Now, the only actions approved with this table, from Users/device/POST and Users/device/delete (which are legal http requests for modification).
And addind/delete rows only allowed from client side using methods Users.Device.subscribe() and Users.Device.unsubscribe().

2018-05-24 04:49 UTC, EGreg requested changes
Please restore the call to Users_Device::delete() 

and case 'device'

2018-05-24 04:49 UTC, EGreg commented on platform/plugins/Users/classes/Users.php
> -				case 'device':
Please restore this. Why did you delete it?

2018-05-24 04:49 UTC, EGreg commented on platform/plugins/Users/classes/Users.php
> -			// forget the device for this user/session
Please restore this code, why did you delete it?

2018-05-24 04:49 UTC, EGreg commented on platform/plugins/Users/handlers/Users/oAuth/post.php
> -	if ($deviceId = Q::ifset($_REQUEST, 'deviceId', null)) {
We need this! Sometimes the "deviceId" is indicated in the request during oAuth, and then you are supposed to add this device. Restore this code.

2018-05-24 04:49 UTC, EGreg commented on platform/plugins/Users/classes/Users.php
> -		if (!empty($device)) {
Restore this stuff. We need this when device is specified during Users::register

2018-05-24 09:54 UTC, AndreyTepaykin commented
The main idea of my changes, is to use one SINGLE method to subscribe and unsubscribe devices.
Adding row to table users_device is not enough to subscribe device. Need also to write some data to client local storage. And notifications will work only if both sides (client and server) have valid data about device. If remove row from users_device table on server, but don't remove from client local storage, Users.Deice.subscribed() method return true (ie device subscribed), because it check subscription only on client (it don't send request to server to check uysers_device table). So if I run Users.Deice.subscribe() method to subscribe device, it will do NOTHING, because it think that device already subscribed. I got this situation many times when debugging notifications. 
So we need:
1. Register devices on client and server synchronously. Because adding row to DB without adding rows to client local storage - not only useless, but even confusing. Exactly this is waht I want to do when try to use Users.Device.subscribe() and Users.Device.unsubscribe() methods only for registering devices.

2. If refuse from prev point, then need to send request to server in method Users.Device.subscribed() to check users_device table. And run Users.Device.subscribed() everytime user subscribed some stream to check whether device vlid subscribed, and if not - subscribe one. Or without Users.Device.subscribed() run Users.Device.subscribe() immediately to subscribe device every time user subscribed to some stream.

2018-05-25 09:52 UTC, AndreyTepaykin commented
Reverted commit "Remove all actions with table users_device from backend". Please look.

2018-05-30 14:52 UTC, closed without merging