Security patches
Qbix/Platform-History-v2 pull request #795
Opened 2018-06-15 13:46 UTC by AndreyTepaykin

Applied patch "Qbix-Platform-1-Modern-Crypto.patch".
After this patch applied, need to do "composer install" when install platform.!!!

Applied "Qbix-Platform-2-Password-Hashing.patch".
Added installation script 1.0.1-Users.mysql and hence increased Users plugin version to 1.0.1

Applied patch "Qbix-Platform-3-Validate-Usernames.patch".
Check $username for unacceptable symbols.

2018-06-15 18:58 UTC, EGreg requested changes
Looks good

2018-06-15 18:58 UTC, EGreg commented on platform/classes/Q/Session.php
> +			$_SESSION['Q']['nonce'] = bin2hex(random_bytes(32));
`random_bytes` is not supported in any PHP lower than 7.

Please make at least a wrapper for this function, in Q.php like this:

`if (!is_callable('randombytes')) {
function random_bytes() {
   // emulate
}
}`

ACTUALLY ParagonIE already has a shim, please download it and include it from `platform/Q.php`

https://github.com/paragonie/random_compat

2018-06-15 19:09 UTC, paragonie-scott commented on platform/classes/Q/Session.php
> +			$_SESSION['Q']['nonce'] = bin2hex(random_bytes(32));
This should already be loaded in via Composer; https://github.com/AndreyTepaykin/Platform/blob/c2f90f735a80a7cd398a94c8d26e978bcc7c09fb/platform/composer.json#L5

2018-06-18 08:44 UTC, AndreyTepaykin commented on platform/classes/Q/Session.php
> +			$_SESSION['Q']['nonce'] = bin2hex(random_bytes(32));
"random_bytes is not supported in any PHP lower than 7." - exactly for this I added composer.json with "paragonie/random_compat": "^2" (PHP 5.x support for random_bytes() and random_int()) to platform. So after platform installed (with "composer install" as well as "npm install"), random_bytes() will usable in PHP 5.x versions. But I added checking whether function random_bytes exist and no use old approach (look my last commit).

"This should already be loaded in via Composer" - what you mean with this? Loaded from where? Currently we have composer.json ony in Users plugin (with only one module "minishlink/web-push").  And we can't use composer.json just in plugins, because we need to use these modules in platform (top level, above plugins).

2018-06-25 04:47 UTC, EGreg approved these changes

2018-06-25 04:47 UTC, merged