Pull request for Facebook photo Selector tool
Qbix/Platform-History-v2 pull request #802
Opened 2018-08-06 12:22 UTC by vyasishanatc194

This is the tool used for facebook photoselector. 

JS used 
- Preview.JS 
- Tool.js 

Streams used :- 
StreamName: Streams/image/album
StreamType: Streams/album

and one script file,  to add streams/image/album for all user.

Please run php install.php --all command to run the script.

2018-08-06 12:25 UTC, vyasishanatc194 commented
conflit solve

2018-08-14 16:00 UTC, EGreg requested changes

2018-08-14 16:00 UTC, EGreg commented on platform/plugins/Streams/web/js/tools/album/preview.js
> +	Q.text.Q.preview = {
Try to use `Q.Text` system instead. This is the old way. The new way loads `en.json` files so update `plugins/Streams/text/Streams/content/en.json` with some appropriately named strings e.g. the tree you have here but under a section named "album"

2018-08-14 16:00 UTC, EGreg commented on platform/plugins/Streams/web/js/tools/album/preview.js
> +					$(".Q_button_local", dialog).on('click', function () {
*Never* just do `$('...')` in tools because this is global selector and it will find elements outside of the tool.

Instead do `tool.$('...')` to do selector only inside of tool, it is same as doing `$(..., tool.element)`. Fix ALL INSTANCES of this in your code.

2018-08-19 03:26 UTC, EGreg approved these changes

2018-08-19 03:26 UTC, merged