Q.notice
Qbix/Platform-History-v2 pull request #861
Opened 2018-10-15 08:06 UTC by AndreyTepaykin

Added Q.Notice API to Q.js and styles to Q.css
Removed old Q.Notice api and it's traces.

2018-10-22 05:12 UTC, EGreg requested changes
Tiny changes

2018-10-22 05:12 UTC, EGreg commented on platform/plugins/Q/web/js/Q.js
> +	 * @param {bool|number} [options.timeOut=false] Time in seconds after which to remove notice.
`timeout` not `timeOut`

2018-10-22 05:12 UTC, EGreg commented on platform/plugins/Q/web/js/Q.js
> +	 * @param {object} options Object of options
Just make all the names uppercase, like `{Object}`

2018-10-22 05:13 UTC, EGreg approved these changes

2018-10-22 05:14 UTC, EGreg requested changes
Tiny changes

2018-10-22 05:14 UTC, EGreg commented on platform/plugins/Q/web/js/Q.js
> +	 * @param {bool|number} [options.timeOut=false] Time in seconds after which to remove notice.
Please fix case:`timeOut` should be `timeout` and all `{foo}` should be `{Foo}`

2018-10-30 16:17 UTC, EGreg approved these changes

2018-10-31 09:00 UTC, AndreyTepaykin commented on platform/plugins/Q/web/js/Q.js
> +	 * @param {bool|number} [options.timeOut=false] Time in seconds after which to remove notice.
Done.

2018-10-31 09:00 UTC, AndreyTepaykin commented on platform/plugins/Q/web/js/Q.js
> +	 * @param {object} options Object of options
Done

2018-10-31 09:00 UTC, AndreyTepaykin commented on platform/plugins/Q/web/js/Q.js
> +	 * @param {bool|number} [options.timeOut=false] Time in seconds after which to remove notice.
Done. Please look last commit.

2018-11-08 01:16 UTC, EGreg approved these changes

2018-11-08 01:16 UTC, merged