Translate notifications
Qbix/Platform-History-v2 pull request #863
Opened 2018-10-16 14:40 UTC by AndreyTepaykin

2018-10-22 04:58 UTC, EGreg requested changes

2018-10-22 04:58 UTC, EGreg commented on platform/classes/Q.php
> +		$options['language'] = isset($params['language']) ? $params['language'] : null;
I don't think options to `Q_Text` should be set from view params. I was wrong, the view should be already receiving translated text, meaning the `$params` should be run through the `Q_Text` translation, and then you call `Q::view()` with those translated params!

2018-10-22 04:58 UTC, EGreg commented on platform/classes/Q/Text.php
> +					$options = array_merge($options, $text);
There is a bug here, you should be doing `$options2 = ...` and using `$options2` later in the `Q_Text::get($text, $options2)` because otherwise as the loop continues, `$options` keeps accumulating more stuff, but it should not.

2018-10-22 04:58 UTC, EGreg commented on platform/plugins/Users/classes/Users.php
> +		return isset($user->preferredLanguage) ? $user->preferredLanguage : Q_Text::$language;
I would have called it `$user->language` to be shorter, but it's too much hassle now I guess, to change it in all databases.

2018-10-22 04:58 UTC, EGreg commented on platform/plugins/Users/handlers/Users/language/post.php
> +		$text = Q_Text::get("Users/content", array('language' => $loggedInUser->preferredLanguage));
I like this! You are using the user's preferred language.
But what if it's null, by default? It should be assigned to `$language` variable which is `"en"` if it's null, use `Q::ifset()` maybe

2018-10-22 05:04 UTC, EGreg requested changes

2018-10-22 05:04 UTC, EGreg commented on platform/classes/Q.php
> +		$options['language'] = isset($params['language']) ? $params['language'] : null;
We shouldn't be setting `$options` from `$params` passed to view. Those are separate things.

Instead, in the calling function, load the translated fields from the correct file using `Q_Text::get()`, save them in `$params` array, and then stick the translated `$params` into the `Q::view()` call

2018-10-22 05:04 UTC, EGreg commented on platform/classes/Q/Text.php
> +					$options = array_merge($options, $text);
Small bug: this should be `$options2 = ...` and below you should use `$options2` because otherwise `$options` will accumulate things as loop continues

2018-10-22 05:04 UTC, EGreg commented on platform/plugins/Users/classes/Users.php
> +		return isset($user->preferredLanguage) ? $user->preferredLanguage : Q_Text::$language;
I wish we had named it `$user->language`, it's shorter, but whatever. It's too late now, right?

2018-10-22 05:04 UTC, EGreg commented on platform/plugins/Users/classes/Users/Email.php
> +		if (!isset($fields['language']) && isset($this->userId)) {
Maybe `getLanguage` should have a default like `"en"` just in case? I don't know

2018-10-22 05:04 UTC, EGreg commented on platform/plugins/Users/handlers/Users/language/post.php
> +		$text = Q_Text::get("Users/content", array('language' => $loggedInUser->preferredLanguage));
I like this! Using the user's own language. But maybe you should use `Users::getLanguage` here, and it should have `"en"` as default, just in case somehow the current preferred language is blank or doesn't correspond to existing language. I don't know.

2018-10-22 05:06 UTC, EGreg requested changes
Please see my requested changes below

2018-10-22 05:07 UTC, EGreg requested changes
Please see my requested changes below

2018-10-22 05:08 UTC, EGreg requested changes
Please see my requested changes below

2018-10-23 08:41 UTC, AndreyTepaykin commented on platform/plugins/Users/classes/Users.php
> +		return isset($user->preferredLanguage) ? $user->preferredLanguage : Q_Text::$language;
I tried first to name field 'language', but it is one of mysql keyphrases. I afraid consistency problems. Please confirm if you want to change field name to 'language'.

2018-10-23 08:50 UTC, AndreyTepaykin commented on platform/plugins/Users/handlers/Users/language/post.php
> +		$text = Q_Text::get("Users/content", array('language' => $loggedInUser->preferredLanguage));
From Q_Text::get() docs: [$options.language=null] Override language
If it null - default language will be applied, which is:
public static $language = 'en';

2018-10-23 09:19 UTC, AndreyTepaykin commented on platform/classes/Q/Text.php
> +					$options = array_merge($options, $text);
Fixed in commit https://github.com/Qbix/Platform/pull/863/commits/1662ff0f256af6e4e879d0b1d5ebed689f3af12d

2018-10-23 09:26 UTC, AndreyTepaykin commented on platform/plugins/Users/classes/Users/Email.php
> +		if (!isset($fields['language']) && isset($this->userId)) {
Yes Users::getLanguage have default language, and it Q_Text::$language:

return isset($user->preferredLanguage) ? $user->preferredLanguage : Q_Text::$language;

2018-10-23 11:33 UTC, AndreyTepaykin commented on platform/classes/Q.php
> +		$options['language'] = isset($params['language']) ? $params['language'] : null;
Modified.
Commit: https://github.com/Qbix/Platform/pull/863/commits/f4eb11c309f21765a021d7dd3033ff90f6153bf3

2018-10-28 00:55 UTC, EGreg approved these changes

2018-10-28 00:57 UTC, EGreg approved these changes

2018-10-28 00:57 UTC, merged