Show notice if subscribed
Qbix/Platform-History-v2 pull request #882
Opened 2018-11-13 14:57 UTC by AndreyTepaykin

Attached subscription rules from streams_subscription_rules table if withParticipant=true

Created method Streams.showNoticeIfSubscribed which check whether user subscribed to stream
 and also whether subscribed to message type (from streams_subscription_rule)

2018-11-16 04:23 UTC, EGreg requested changes

2018-11-16 04:23 UTC, EGreg commented on platform/plugins/Streams/web/js/Streams.js
> +		if ($.inArray(messageType, Q.getObject("types", streamsSubscribeRulesFilter) || []) >= 0) {
Please do not use $.inArray, we do not rely on jQuery on Q core libraries. Use Array.prototype.indexOf which we have defined in Q.js or just do a loop please

2018-11-27 12:59 UTC, AndreyTepaykin commented on platform/plugins/Streams/web/js/Streams.js
> +		if ($.inArray(messageType, Q.getObject("types", streamsSubscribeRulesFilter) || []) >= 0) {
Done in last commit.

2018-12-04 22:34 UTC, EGreg approved these changes

2018-12-04 22:35 UTC, EGreg approved these changes

2018-12-04 22:35 UTC, EGreg commented on platform/plugins/Streams/web/js/Streams.js
> +		Q.Template.set('Streams/followup/mobile/alert', Q.getObject(["followup", "mobile", "alert"], text));
In the future consider doing

`var s = Q.Template.set; s(...) s(...)`
to avoid copypasting a lot of code

2018-12-04 22:35 UTC, merged