Streams access
Qbix/Platform-History-v2 pull request #892
Opened 2018-11-28 13:14 UTC by AndreyTepaykin

When trying add/update row to users_contact, I get errors:
Column 'gender' cannot be null
Column 'lastName' cannot be null
We need to set these fields default null. Because communities users have no lastName and gender.

When trying to add row with empty publisherId to streams_access table (from installation script), I get error from Streams_Avatar::updateAvatar method: "publisherId empty".
So decided to move this method under condition if(!empty($this->publisherId)).

2018-12-04 22:29 UTC, EGreg commented on platform/plugins/Streams/classes/Streams/Access.php
> +			Streams_Avatar::updateAvatars($this->publisherId, $tainted_access, $this->streamName);
Why did you move it inside the `if`?

2018-12-05 12:24 UTC, AndreyTepaykin commented on platform/plugins/Streams/classes/Streams/Access.php
> +			Streams_Avatar::updateAvatars($this->publisherId, $tainted_access, $this->streamName);
**I described in commit description:**
When trying to add row with empty publisherId to streams_access table (from installation script), I get error from Streams_Avatar::updateAvatar method: "publisherId empty".
So decided to move this method under condition if(!empty($this->publisherId)).

2018-12-05 12:27 UTC, EGreg requested changes

2018-12-05 12:27 UTC, EGreg commented on platform/plugins/Streams/classes/Streams/Access.php
> +			Streams_Avatar::updateAvatars($this->publisherId, $tainted_access, $this->streamName);
But listen, this `if` is more than just about `publisherId`. You should break up the `if` into the top line, and then `!in_array())` should be separate `if` inside it, I think.

I don't know ... updateAvatars for templates and mutable? May be useful.

2018-12-05 16:09 UTC, EGreg approved these changes

2018-12-05 16:09 UTC, merged