Can write to path
Qbix/Platform-History-v2 pull request #893
Opened 2018-11-28 14:44 UTC by AndreyTepaykin

Added method Users::byRoles which return array of users_contact rows where user assigned by labels.

Added to permitted paths also paths for users where logged user assigned as Communities/admins or Users/owners.

2018-12-01 18:42 UTC, EGreg requested changes
You need to put ["Users/admins", "Users/owners"] (note: NOT Communities/admins) inside `Users/config/plugin.json` under `Users/icon/canManage`, so it is available to all projects as default.

2018-12-03 15:10 UTC, AndreyTepaykin commented
I want to clarify roles.
Now we have Communities/admins, Users/admins, Users/owners, Users/members, Users/guests
under Users/roles in Communities/config/plugins.json
Is it correct?
And also I have Users/icon/canManage: ["Communities/admins", "Users/owners"]  in Communities/config/plugins.json
but you want to move canManage to Users/config/plugins.json right?
And allow to manage icons only for Users/admins and Users/owners but not Communities/admins
right?

2018-12-04 22:24 UTC, EGreg commented
> I want to clarify roles.
> Now we have Communities/admins, Users/admins, Users/owners, Users/members, Users/guests
> under Users/roles in Communities/config/plugins.json
> Is it correct?
> And also I have Users/icon/canManage: ["Communities/admins", "Users/owners"] in Communities/config/plugins.json
> but you want to move canManage to Users/config/plugins.json right?
> And allow to manage icons only for Users/admins and Users/owners but not Communities/admins
> right?
> I think you want to refuse from Communities/admins role and use Users/admins instead.
> Please confirm if I right.

As we spoke today, we should have `Users/admins` and `Users/owners` not Communities
Please make appropriate changes and then I can pull

2018-12-05 11:58 UTC, EGreg approved these changes

2018-12-05 11:58 UTC, merged