Modified Users::byRoles method.
Qbix/Platform-History-v2 pull request #908
Opened 2018-12-10 13:08 UTC by AndreyTepaykin

Set $filter argument required and if it null - return empty array of rows.
Because otherwise we just return array of rows where userId in contactUserId field.

2018-12-21 03:33 UTC, EGreg requested changes
Why `$filter` is required? There are calls to `::byRoles()` in the code which do not provide any parameters, this will cause an error for them. Besides this ... why do we need to filter the roles? What if I want to just find everyone that I have roles to? This is intended behavior.

2018-12-21 13:25 UTC, AndreyTepaykin commented
I think you confuse this method with Users::roles(). 
If need to find everyone that I have roles to, you can do 
Users_Contact::select()->where(array('contactUserId' => $userId))->fetchDbRows()
just one row.
That is why I decided to make $filter required. Because this method return rows by labels.
And I fixed all calls Users::byRoles with $filter argument. Nowhere Users::byRoles without $filter.

2018-12-23 17:01 UTC, EGreg commented
I think `$filter` should be optional. It seems both methods `Users::roles()` and `Users::byRoles()` are exactly the same, except first one takes *only one* publisher and other one contacts for multiple publishers. So they should behave similarly. What do you lose by having a default `filter = null`? Nothing.

2018-12-24 13:45 UTC, AndreyTepaykin commented
Modified method Users::byRoles
Make $filter argument optional.

2018-12-27 02:42 UTC, EGreg approved these changes

2018-12-27 02:43 UTC, merged